/*
    Copyright (C) 2014 Parrot SA

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in
      the documentation and/or other materials provided with the 
      distribution.
    * Neither the name of Parrot nor the names
      of its contributors may be used to endorse or promote products
      derived from this software without specific prior written
      permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
    AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
    OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
    SUCH DAMAGE.
*/
/**********************************************************
 *            AUTOGENERATED FILE                          *
 *             DO NOT MODIFY IT                           *
 *                                                        *
 * To add new commands :                                  *
 *  - Modify ../Xml/commands.xml file                     *
 *  - Re-run generateDeviceControllerCategories.py script *
 *                                                        *
 **********************************************************/
#import <libARSAL/ARSAL.h>
#import "DeviceControllerProtected.h"
#import "MiniDroneDeviceController+libARCommandsDebug.h"
#ifdef ARCOMMANDS_HAS_DEBUG_COMMANDS


@implementation MiniDroneDeviceController (libARCommandsDebug)
const char *MiniDroneDeviceControllerDebug_TAG = "MiniDrone DeviceController";

#pragma mark static C callback

- (void)registerMiniDroneDebugARCommandsCallbacks
{
}

- (void)unregisterMiniDroneDebugARCommandsCallbacks
{
}

#pragma mark ARCommands sending function 
    // Command class Debug
- (BOOL)MiniDroneDeviceController_SendDebugTest1:(int)bufferId withSendPolicy:(eARNETWORK_SEND_POLICY)policy withCompletionBlock:(DeviceControllerCompletionBlock)completionBlock withT1Args:(int8_t)t1Args
{
    u_int8_t cmdbuf[128];
    int32_t actualSize = 0;
    eARCOMMANDS_GENERATOR_ERROR cmdError;
    BOOL sentStatus;

    // Send Test1 command
    sentStatus = NO;
    cmdError = ARCOMMANDS_Generator_GenerateMiniDroneDebugDebugTest1(cmdbuf, sizeof(cmdbuf), &actualSize, t1Args);
    if (cmdError == ARCOMMANDS_GENERATOR_OK)
    {
        sentStatus = [self sendData:cmdbuf withSize:actualSize onBufferWithId:bufferId withSendPolicy:policy withCompletionBlock:completionBlock];
    }
    if (!sentStatus)
    {
        ARSAL_PRINT(ARSAL_PRINT_ERROR, MiniDroneDeviceControllerDebug_TAG, "Failed to send Test1 command.");
    }

    return sentStatus;
}
- (BOOL)MiniDroneDeviceController_SendDebugTest2:(int)bufferId withSendPolicy:(eARNETWORK_SEND_POLICY)policy withCompletionBlock:(DeviceControllerCompletionBlock)completionBlock withT2Args:(int8_t)t2Args
{
    u_int8_t cmdbuf[128];
    int32_t actualSize = 0;
    eARCOMMANDS_GENERATOR_ERROR cmdError;
    BOOL sentStatus;

    // Send Test2 command
    sentStatus = NO;
    cmdError = ARCOMMANDS_Generator_GenerateMiniDroneDebugDebugTest2(cmdbuf, sizeof(cmdbuf), &actualSize, t2Args);
    if (cmdError == ARCOMMANDS_GENERATOR_OK)
    {
        sentStatus = [self sendData:cmdbuf withSize:actualSize onBufferWithId:bufferId withSendPolicy:policy withCompletionBlock:completionBlock];
    }
    if (!sentStatus)
    {
        ARSAL_PRINT(ARSAL_PRINT_ERROR, MiniDroneDeviceControllerDebug_TAG, "Failed to send Test2 command.");
    }

    return sentStatus;
}
- (BOOL)MiniDroneDeviceController_SendDebugTest3:(int)bufferId withSendPolicy:(eARNETWORK_SEND_POLICY)policy withCompletionBlock:(DeviceControllerCompletionBlock)completionBlock withT3Args:(int8_t)t3Args
{
    u_int8_t cmdbuf[128];
    int32_t actualSize = 0;
    eARCOMMANDS_GENERATOR_ERROR cmdError;
    BOOL sentStatus;

    // Send Test3 command
    sentStatus = NO;
    cmdError = ARCOMMANDS_Generator_GenerateMiniDroneDebugDebugTest3(cmdbuf, sizeof(cmdbuf), &actualSize, t3Args);
    if (cmdError == ARCOMMANDS_GENERATOR_OK)
    {
        sentStatus = [self sendData:cmdbuf withSize:actualSize onBufferWithId:bufferId withSendPolicy:policy withCompletionBlock:completionBlock];
    }
    if (!sentStatus)
    {
        ARSAL_PRINT(ARSAL_PRINT_ERROR, MiniDroneDeviceControllerDebug_TAG, "Failed to send Test3 command.");
    }

    return sentStatus;
}
@end

#endif // ARCOMMANDS_HAS_DEBUG_COMMANDS
// END GENERATED CODE
